name: 功能要求
description: 我想要一些功能！
labels: ["feature request"]
title: "[FEATURE REQUEST] <title>"
body:
  - type: markdown
    attributes:
      value: |
        ## 功能说明

  - type: textarea
    validations:
      required: true
    attributes:
      label: 想要什么功能呢？
      description: 简单说一下吧。

  - type: checkboxes
    validations:
      required: true
    attributes:
      label: 是什么方面的呢？
      options:
        - label: 前端(网页)
        - label: 后端(API)
        - label: 其它

  - type: markdown
    attributes:
      value: |
        ## 开发状态

  - type: checkboxes
    attributes:
      label: 自己开发吗？
      options:
        - label: 我会自己提 PR 来完成

  - type: textarea
    attributes:
      label: 已有的 PR
      description: >-
        可以回头用编辑来填这个。

  - type: markdown
    attributes:
      value: |
        ## 其它

  - type: textarea
    attributes:
      label: 其它信息
      description: 还有什么补充的吗？请写在这里吧！
