import "./software/subapp/bilibili"
import "./software/subapp/chrome"
import "./software/subapp/clion"
import "./software/subapp/cloud-music"
import "./software/subapp/dingtalk"
import "./software/subapp/edge"
import "./software/subapp/everything"
import "./software/subapp/temurin"
